version: '3'
services:
  client:
    build:
      context: client/
      target: development
    command: npm run dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: server/
      target: development
    command: npm run start:dev
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    env_file:
      - server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sunny-days-app
      - POSTGRES_PASSWORD=PostgresPassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2-rc1-alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: always
    ports:
      - 6379:6379
    env_file:
      - server/.env
    volumes:
      - redis-data:/data

volumes:
  db-data: {}
  redis-data: {}